### ISSUE TITLE
Let users login and logout

### ISSUE THREAD

**Issue by naz-hage** [ahmdhjj92/cv-builder#7]

**Comment by ahmdhjj92** [comment]
This issue and pull request #5 can be closed and the branch 'users' can be merged into 'main' once all these requirements are fulfilled:

1. Users can log in if their credentials exit; an error should be shown otherwise and the login form must be submitted again.

2. Users can register and their registration form should be validated (otherwise alert messages will appear and the user has to fill the form again) in the following manner:

- All fields are required.
- Username and emails must be unique.
- Passwords should match their confirmation field.
- Email must be a valid email address, username must match [Django's own requirements](https://docs.djangoproject.com/en/3.2/ref/contrib/auth/#django.contrib.auth.models.User.username), same goes for [password validation](https://docs.djangoproject.com/en/3.2/topics/auth/passwords/#module-django.contrib.auth.password_validation).

3. Attempts to login or register while logged in should have special views that don't show the original forms but offer other options such as logout or go to homepage.

4. A footer is added to the base layout so all actions regarding user authentication (login,logout, register, admin login) can be accessed and tested easily, links to 'home' and 'about' page should be added too.

> Note that future issues and pull requests would focus on only one particular task.
